### ISSUE TITLE
Port over the trapezoid fitter from DAVE

### ISSUE THREAD

**Issue by mustaric** [spacetelescope/exovetter#13]
We need a trapezoid fitter separate from each of the vetters.

**Comment by pllim** [comment]
By DAVE, you mean https://github.com/exoplanetvetting/DAVE ? It has MIT license, so should be okay to port over.

Did @fergalm mean everything inside https://github.com/exoplanetvetting/DAVE/tree/master/trapezoidFit ?

**Comment by mustaric** [comment]
Yes to both.

We will need to wrap the trapezoidFit so it takes the same TCE and lightkurve objects, just like one of the vetters.

**Comment by pllim** [comment]
Okay, so I guess this is blocked by #12. Also, exactly which "lightkurve objects" do you mean? I have never used `lightkurve` before.
