### ISSUE TITLE
Add odd/even test

### ISSUE THREAD

**Issue by mustaric** [spacetelescope/exovetter#23]
Add a vetter that takes a light curve and tce  and determine the difference between the depths of the odd and the even transits. It should return both depths and the errors.  Usually a cut is  made when significant depth differences are seen.

The astropy BLS code actually is one path forward for this test.

**Comment by pllim** [comment]
Some implementation exists (#27) but needs to polish the API.

**Comment by pllim** [comment]
Superseded by #29
